name: Publish Package

on:
    release:
        types: [ published ]

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Publish package
      run: |
        npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
        npm publish --ignore-scripts
