name: Publish Package

on:
    release:
        types: [ published ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: $GITHUB_REF
      env:
        GITHUB_REF: ${{ secrets.GITHUB_REF }}
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: npm ci
    - name: Publish package
      run: |
        npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
        npm publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
