name: Storybook

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Deploy Storybook
        run: npm run storybook:deploy -- --ci
        env:
          GH_TOKEN: matthewdowns:${{ secrets.GITHUB_TOKEN }}
